
version: 2

run:
  timeout: 5m
  skip-dirs:
    - vendor/

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: false

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true