run:
  timeout: 5m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  unused:
    check-exported: false

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - unused
    - typecheck
    - staticcheck
    - gosimple
    - stylecheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor/
    - internal/database/migrations
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
