
version: 2

run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor/
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    shadow: false

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - unused