# .github/workflows/go.yml
name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine  # Usando a mesma versão do seu docker-compose
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: futebol_stats
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          # Instalações adicionais necessárias
          go install mvdan.cc/gofumpt@latest
          sudo apt-get update && sudo apt-get install -y bc

      - name: Check formatting
        run: |
          if [ -n "$(gofumpt -l .)" ]; then
            echo "The following files are not formatted properly:"
            gofumpt -l .
            exit 1
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          # Adicionar opção para usar cache se necessário
          # skip-cache: false

      - name: Run tests with coverage
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          go tool cover -func=coverage.txt | tee coverage_output.txt
          total_coverage=$(grep total coverage_output.txt | awk '{print $3}' | sed 's/%//')
          echo "Total coverage: $total_coverage%"
          if (( $(echo "$total_coverage < 95" | bc -l) )); then
            echo "Test coverage ($total_coverage%) is below threshold (95%)"
            exit 1
          fi

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # Verifique se este slug está correto para o seu repositório
          slug: dinho-carvalho/fut-app
          file: ./coverage.txt
          fail_ci_if_error: true

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Build
        run: go build -v ./...

      # Opcional: Adicione um passo de build Docker se necessário
      # - name: Build Docker image
      #   run: docker build -t futebol-stats:${{ github.sha }} .